services:
  sharing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-8080}
    container_name: file-sharing-service
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    environment:
      # Override specific settings if needed
      - DB_PATH=/app/data/sharing.db
    volumes:
      - ./data:/app/data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${PORT:-8080}/health",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - sharing-network

networks:
  sharing-network:
    driver: bridge
